# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Payment Confirmation

# Model Form Field configuration
form: $/octommerce/octommerce/models/paymentconfirmation/fields.yaml

# Model Class name
modelClass: Octommerce\Octommerce\Models\PaymentConfirmation

# Default redirect location
defaultRedirect: octommerce/octommerce/paymentconfirmation

# Create page
create:
    title: Create Payment Confirmation
    redirect: octommerce/octommerce/paymentconfirmation/update/:id
    redirectClose: octommerce/octommerce/paymentconfirmation

# Update page
update:
    title: Edit Payment Confirmation
    redirect: octommerce/octommerce/paymentconfirmation
    redirectClose: octommerce/octommerce/paymentconfirmation

# Preview page
preview:
    title: Preview Payment Confirmation