# ===================================
#  Relation Behavior Config
# ===================================

products:
    label: Product
    form: ~/plugins/octommerce/octommerce/models/product/fields.yaml
    deferredBinding: true
    view:
        list: ~/plugins/octommerce/octommerce/models/product/columns.yaml
        toolbarButtons: add|remove
        showCheckboxes: true
    manage:
        list: ~/plugins/octommerce/octommerce/models/product/columns.yaml
        showSearch: true