# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Order Status

# Model Form Field configuration
form: $/octommerce/octommerce/models/orderstatus/fields.yaml

# Model Class name
modelClass: Octommerce\Octommerce\Models\OrderStatus

# Default redirect location
defaultRedirect: octommerce/octommerce/orderstatuses

# Create page
create:
    title: Create Order Status
    redirect: octommerce/octommerce/orderstatuses/update/:code
    redirectClose: octommerce/octommerce/orderstatuses

# Update page
update:
    title: Edit Order Status
    redirect: octommerce/octommerce/orderstatuses
    redirectClose: octommerce/octommerce/orderstatuses

# Preview page
preview:
    title: Preview Order Status
