scopes:
    status:
        label: Status
        modelClass: Octommerce\Octommerce\Models\OrderStatus
        nameFrom: name
        conditions: status_code in (:filtered)
    paymentMethod:
        label: Payment Method
        modelClass: Responsiv\Pay\Models\PaymentMethod
        nameFrom: name
        scope: FilterPaymentMethods